### ISSUE TITLE
Revert 773$w and 774$w to just MMS ID, no prefix

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/lsp-data#8]
We changed all 773 and 774 fields to conform with the MARC specification, which requires that an institution's MARC prefix is added to the 773$w and 774$w.

Unfortunately, Alma does not allow the prefix. So, we have to revert all 773$w and 774$w with `(NjP)[MMS ID]` to 773$w and 774$2 of `[MMS ID]`.

We must add back the `(NjP)` prefix when we publish records to OCLC and Orangelight.

Acceptance criteria:
- [x] Code is made and tested in marc_cleanup to remove a string from the beginning of subfields and fields provided as parameters
- [x] A script is made in lsp-data to export stub records with MMS ID, updated 773 fields, and updated 774 fields
- [x] A merge rule is created for one-time use and documented in a ticket in alma-config
- [x] The stub records are loaded into Alma sandbox using the `MMS ID Match with Merge Rule` import profile with the above Merge Rule applied
- [x] The stub records are loaded into Alma production using the `MMS ID Match with Merge Rule` import profile
- [x] The import profile is deactivated in production after use
- [x] The merge rule is deleted from production after use

**Comment by doncat** [comment]
Request from RBCat & Omega end processing: Absence of related holdings in Alma display is noticeable. You have to look at the BIB to see why. Reverting would be helpful.

**Comment by mzelesky** [comment]
Thanks for the input! Since it is near the top of the Ready column, it should be done soon, likely in the next sprint.

**Comment by mzelesky** [comment]
@doncat All 773 and 774 fields have been reverted. I am already seeing the record links for most of them.
